name: Build
on:
  create:
    tags:
       - 'v*.*'
    
jobs:
  docker_build_push:
    env:
      GIT_REF: ${{ github.ref }}
    if: startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest
    steps:
    - name: Extract Git Tag
      run: |
        VERS_TAG=$(echo $GIT_REF | sed 's/refs\/tags\/v//g')
        VERS_TAG="\"$VERS_TAG"\"
    - name: Write Tag to Scala Build Version
      run: |
        cd csvw-check
        sed -i "s/version := *.*/version := $VERS_TAG/" build.sbt
    - name: Set up Scala
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 11
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build
      run: sbt docker:publishLocal
    - name: Push
      run: |
        vers_num="$(grep 'version :=' build.sbt | head -n1 | sed 's/.*"\(.*\)".*/\1/')"
        local_param="csvw-check:$vers_num"
        push_param="gsscogs/csvw-check:v$vers_num"
        docker tag $local_param $push_param
        docker push $push_param
